### ISSUE TITLE
NaN and undefined flashes under the title of the space

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1385]
The first time we initialize a space, we don't know how much time it spans. During the brief moment we are fetching that data, the duration is "NaN". It should simply not be shown. The size also shows "undefined" for a moment. It should simply be hidden too.

![image.png](https://images.zenhubusercontent.com/5e8cea85d10cba8a99efeb34/81e73f7e-27cd-4ede-ba8b-fb991cc75875)

**Comment by philrz** [comment]
I've confirmed with @jameskerr that this one is no longer valid and can be closed. Some reasons:

1. The concept of “Spaces” are behind us
2. The app is no longer showing partial results during pcap import, so that source of "flashing" is gone
3. The first thing the user now sees as the end of a pcap import is a pool summary page that doesn’t show duration/size, so the stuff that was erroneously flashing in the pat no longer appears
