### ISSUE TITLE
Add space summary view

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/brim#1477]
In a recent blog draft, Oliver needed to instruct users to right-click on a space name & select 'Rename' in order copy the space's name. This reminded me that we've discussed having a space 'summary' pane in the past, that could display its name, storage details, space id, and more. We should do that, and make sure that all of the information there is easily copy-and-paste-able for users that want are using Brim to get information to feed into zapi or other non-Brim clients.

**Comment by philrz** [comment]
I suppose this would justify a separate issue if folks agree it's worth doing, but for things like renaming or highlighting its name in order to copy & paste it, it seems like we could also mimic the behaviors of Finder/Explorer utilities, e.g. single-clicking an entry that you've already highlighted activates a cursor such that you can rename, or you could Command+c/Control+c to copy into paste buffer, etc. I do agree that the summary pane would still have its uses for getting the details/id/etc., but we could avoid making users enter another view just to do those simplest operations.

**Comment by jameskerr** [comment]
@alfred-landrum , @philrz I think both of your ideas are correct. We should have a rename-in-place feature activated in an easy way, then also a space details modal that would display info similar to the workspace info modal we have.

**Comment by philrz** [comment]
As of current Brim commit 91b323d, this "summary view" exists for pools. As shown in the attached video, this text is well-suited for cut & paste into other contexts. More info will surely be added to the page over time (e.g., #710).

https://user-images.githubusercontent.com/5934157/187545710-3a2954ce-e3f7-4732-b1fc-f2123da2e69c.mp4

As for the separate topic of rename-in-place mentioned above, I've opened issue #2508 to track that.

Closing this one.
