### ISSUE TITLE
Replace Brim release process with "electron-builder"

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#1487]
We currently use a modular solution for the release process which includes `electron-packager` (packaging), `electron-winstaller` (windows installer), `electron-installer-dmg` (mac), `electron-installer-debian`, `electron-installer-redhat`, `electron-installer-zip`, `electron-notorize` (for signing). The packager we currently use does not facilitate registering custom app protocols (`brim://`) for all OSs, just MacOS, which is now a requirement for our authentication mechanism.

Instead of seeking additional modular solutions, let's use [electron-builder](https://www.electron.build/) for this whole process instead. It describes itself as "A complete solution to package and build a ready for distribution Electron app for macOS, Windows and Linux with “auto update” support out of the box". After spending some time seeing how feasible it would be to make this transplant, I've found that the transition should be relatively straightforward.

The primary cost comes with the fact that iteration speed is slow since it depends on building a release with each configuration attempt, as well as that we would need to verify several of the components that this new mechanism would be managing. The following is a list of those components:

**macOS**
- [x] Build release
- [x] Sign release (includes entitlements necessary for suricata updates)
- [x] Notorize release 
- [x] Install custom brim protocol 
- [x] Verify autoupdate

**Windows**
- [x] Build release
- [x] Sign release
- [x] Install custom brim protocol 
- [ ] Verify autoupdate

**Linux**
- [x] Build release
   - [x] Create installer for `debian`
   - [x] Create installer for `redhat`
- [x] Install custom brim protocol 
- [x] Verify autoupdate

**Comment by philrz** [comment]
Summarizing a Slack conversation @mason-fish and I just had about my personal stake in this topic:

1. The installer animation on Windows would likely improve. We recently put some effort into replacing the default one in `electron-winstaller` with something branded and less-confusing. But @mason-fish was able to show me a screenshot of what we'd get with the move to `electron-builder`, which is not only branded but has a progress bar!

![image](https://user-images.githubusercontent.com/5934157/109348701-be803e80-7829-11eb-81e5-616336f5f1f1.png)

Regarding the Windows Explorer & Settings/Control Panel icons we recently made branded in `electron-winstaller`, @mason-fish also confirmed that he already has these working as branded in `electron-builder` as well.

![image](https://user-images.githubusercontent.com/5934157/109348838-e4a5de80-7829-11eb-96f5-a185a2d79b70.png)

![image](https://user-images.githubusercontent.com/5934157/109348860-ecfe1980-7829-11eb-909e-07f603a0b06f.png)

2. I asked about if `electron-builder` makes it easy to create the Windows build from a dev environment on macOS, as the Wine-based way this used to be workable has not worked for some time, since Wine stopped working on macOS a while back. @mason-fish confirmed that so far he's had to do his stuff in a true Windows VM in parallels, but he also noted that he'd found a Docker-Wine-based approach described at https://www.electron.build/multi-platform-build#to-build-app-for-windows-on-linux that we could look into. We also agreed that the current build process based on GitHub Actions is working ok (its main drawback is that it just takes time) so we probably don't need to make this a priority for the current effort.

3. To that end, we'll want to make sure the nightly build process still works reliably at the end of all this. I'll be sure to do my own testing of that.

**Comment by philrz** [comment]
[#1563](https://github.com/brimdata/brim/issues/1563) tracks some loose ends related to this transition we'll likely want to address before we create our next GA release using electron-builder. Otherwise, the build system is creating nightly builds and is ready to go.

Thanks @mason-fish!
