### ISSUE TITLE
Update Windows signing certificate

### ISSUE THREAD

**Issue by alfred-landrum** [brimdata/brim#1488]

**Comment by philrz** [comment]
Our cert renewal is currently "pending" with DigiCert. The process unfortunately stalled because they need to be able to see our current corporate contact info in our DUNS record and it unfortunately had not been updated to reflect our state after a recent office move. The updated docs have been uploaded to the relevant parties but we're told it may take about a week to get processed, then we can update our DUNS info, then we can have DigiCert contact us using that information for verification, then our renewal should go through. :sweat\_smile:

**Comment by philrz** [comment]
This procedure is completed and we're successfully generating signed Windows builds again. There's a Brim-internal doc at [https://lookylabs.atlassian.net/wiki/spaces/PROD/pages/391315475/Windows+Code+Signing](https://lookylabs.atlassian.net/wiki/spaces/PROD/pages/391315475/Windows+Code+Signing) that describes the details.
