### ISSUE TITLE
Conditional Packets Button

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1539]
For the next release, the "security module" will be considered "installed" if there is the presence of a `brimcap` executable on the user's system.

If the security module is installed, show the packets button like it is now. If not, remove it from the toolbar. 

- [ ] The packets button in the search window
- [ ] The packets button in the detail window

**Comment by philrz** [comment]
Verified in Brim commit [6078840](https://github.com/brimdata/brim/commit/60788403eb0ad0f454278571e45a68b971a9379f) talks to `zed` commit `aa4170e`.

As shown in the attached video, if the `brimcap` binary is deleted from the `zdeps/` directory, then the Reload option is selected from the pull-down menu, the shark fin is no longer present.

https://user-images.githubusercontent.com/5934157/116641859-73b29e00-a922-11eb-84fc-bd0ca5f88ab0.mp4

Since Brimcap is now bundled with the app and hence is expected to always be available, this is functionality that probably won't be invoked for some time. However, since we envision a future that includes non-pcap users, if Brimcap should become a post-install, add-on plugin, this will become useful to keep the UX from being unnecessarily cluttered for users that would otherwise not understand the role of the button.

Thanks @mason-fish!
