### ISSUE TITLE
Release Notes Tab Upon Upgrade

### ISSUE THREAD

**Issue by philrz** [brimdata/brim#1594]
When discussing the plan for #1593, we recognized it would be a helpful courtesy to the user if we pop up a notification upon upgrade that describes in brief what has changed and offers a link to the article described in brimdata/brimcap#64 so they know they need to recreate a new config if they want to continue using the customizations they had before.

While this should help us with the tactical problem of guiding users through this specific Preferences transition, during the discussion we recognized that this is helpful functionality we might want to use in future upgrades generally, i.e. (similar to other apps) a "What's New" pop-up that displays or links to the Release Notes or other content relevant to the upgrade. This seems like good practice since, especially given the app's tendency to auto-update, we can't always assume users are going to read the Release Notes and pay attention to important changes. Anything we can do to put this content front & center should help avoid user frustration or excess support load.

When first proposing this I imagined this initial notification only being specific to if the user had populated any of those three Preferences settings. However, on further reflection I realize it probably would not be a bad thing to notify _all_ users just in case, e.g. maybe a user _had_ changed those settings at one time, then reverted them to their default blank state, but would still benefit from knowing about the change for the next time they need it. Considering all the other new stuff we're planning to introduce in the next GA release, I'm guessing we'll think of other content/links to add to a general "everybody sees it" notification, so I hereby walk back that initial part of my proposal, and hopefully that simplifies the implementation somewhat. :smile:

**Comment by jameskerr** [comment]
# Release Notes Tab

Each Brim release usually has some interesting new features or changes. Showing the release notes from within the app is an effective way to communicate these with our users.

The new functionality will include:

1. An app menu item called at `Help => Release Notes`
2. A `<ReleaseNotes />` component to fetch and render the release notes
3. An initializer function to open the release notes in a new tab if it's the first time running that particular version.



### App Menu Item

When clicked it will open the release notes for the current version of the running app in a new tab on the active browser window. If there are no browser windows open, it will create one.



### Component

The component will request the markdown description using the github rest api.

This is easliy done with their public api. Here is the curl and jq recipe to get the release description from v0.24.0.

```
curl   -H "Accept: application/vnd.github.v3+json"  \
 https://api.github.com/repos/brimdata/brim/releases/tags/v0.24.0 | jq '.body'
```

If there is no description, it will say "No release notes for version: <num>." If there is a network error, say, "Could not connect to the network."

Otherwise, run in through the [markdown-it parser](https://github.com/markdown-it/markdown-it) to convert it to html. Make sure that markdown-it does a good job sanitizing the input. All links must be converted to open in an external program. Make the container scrollable in case the release notes are long. And be sure to handle anchor tags that link to subsections of the notes.

The URL to render this component should simply be "/release-notes". Make sure that it is displayable with or without a workspace. 



### Initializer

On startup, check to see if the release notes have already been presented to the user. If so, do nothing, otherwise open a new tab with the release notes url and mark that the user has been shown the release notes for that version. This should be stored in redux with a simple reducer. `last-running-version: "v0.24.0"`. It would be global state.

It might be nice to have a class to handle these methods.

```
class VersionLaunch {
  first()
  record()
}

let launch = new VersionLaunch()

if (launch.first()) {
  tabs.new("/release-notes")
  launch.record()
}
```



### Additional Features

Using this approach, we can create other tab content like "Welcome", and "Getting Started".

**Comment by philrz** [comment]
@jameskerr: The proposal looks great! FWIW, I don't _think_ I've ever used anchors when constructing release notes, but given your proposal to cover things like Welcome & Getting Started through the same implementation, who knows when it might come up, so I'm glad you thought of it. :+1:

**Comment by mason-fish** [comment]
Lgtm!

One question: What do we want to do about the left pane? I'd normally vote to keep it so that users can maintain a single-tab experience, but as is the left pane only works if there is a current workspace set. And when none is set then we use the tab content area to show a workspace chooser page, which would cause some logic conflict in the case that the content should be the release-notes.
