### ISSUE TITLE
Zed Lang Update

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1644]
Update the app to use the updated language described in the zed pr: https://github.com/brimdata/zed/pull/2692

**Comment by philrz** [comment]
Verified in Brim commit 43b0ed5 via nightly macOS build [https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg.](https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-43b0ed51.0/macos/Brim-0.25.0-prerelease-43b0ed51.0.dmg).

To verify, I started with a common test wrccdc pcap imported into GA Brim `v0.24.0` and ran through all the Query Library entries that were updated due to the language changes in the linked PR. That's shown in this first video.

https://user-images.githubusercontent.com/5934157/118417679-1597f180-b66a-11eb-9de5-cab6fce908b5.mp4

Then after upgrading to the newer Brim at commit 43b0ed5, in the second video I run through the same queries and eyeball the results to confirm the results look similar, which they do. (In one of them the rows appear different, but I can see that's because the pipeline lacks a `| sort` and it happens to show an aggregation result, and it's known that Zed does not guarantee deterministic order on aggregation outputs.)

https://user-images.githubusercontent.com/5934157/118417701-25afd100-b66a-11eb-8ff4-f27293fe646d.mp4

Overall this exercise provides a handy way to see some of the more significant language changes, e.g.:

* What was `_path=dns` now becomes `_path=="dns"` (i.e. the explicit `==` operator is now used for testing equality rather than overloading `=` as was the case int he past... also, quotes are required because we're checking for equality to a string value, whereas without the quotes we'd be attempting to compare against the contents of a field named `dns`)
* What was `_path=~smb*` now becomes `_path matches smb*` (i.e. there's a new syntax for doing glob matches against the contents of a named field)
* What was `put classnet=network_of(id.resp_h)` now becomes `put classnet := network_of(id.resp_h)` (i.e. the explicit `:=` operator is now used for assignment rather than overloading `=` as was the case in the past)

As it turns out, comparing the outputs of the "Suricata Alerts by Subnet" entry led me to notice unrelated issue https://github.com/brimdata/zed/issues/2728.

Thanks @jameskerr!
