### ISSUE TITLE
Use brimcap analyze instead of load

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#1716]
The brimcap plugin currently invokes `brimcap load` when it encounters pcaps. Within the `brimcap` tool, that load operation ultimately uses the deprecated `POST /pool/{id}/logs` endpoint which does not publish its completion of the commit as an event sent back to the app to inform it of potential stale data.

The fastest fix could be to add the publishing logic to the deprecated endpoint's handler. However, since we want to move the app to the commit model anyway, let's instead let the brimcap plugin handle this logic by invoking `brimcap analyze` then make the add/commit api requests itself, piping the data from `brimcap` into the request.

This way, the commit event will be properly published and the app will be notified of the change in data.

**Comment by philrz** [comment]
@mason-fish: Since `brimcap load` also populates the packet index, I assume a separate invocation of `brimcap index` will now also need to be a part of this effort, correct?

**Comment by mason-fish** [comment]
@philrz Yep that's right

**Comment by philrz** [comment]
Verified on Brim commit dab9821 on macOS using nightly build https://storage.googleapis.com/brimsec-releases/brim/v0.25.0-prerelease-dab9821b.0/macos/Brim-0.25.0-prerelease-dab9821b.0.dmg.

As shown in the attached video, when dragging a pcap into the app, we can see from `ps` output that `brimcap analyze` is now being used instead of `brimcap load`. Once the pcap is loaded, I can hit the **Packets** button and extract a flow based on a log entry as has always been true in the past.

https://user-images.githubusercontent.com/5934157/125180529-e4422a80-e1af-11eb-8662-bd36f0d27299.mp4

Here's the same verification on Windows 10.

https://user-images.githubusercontent.com/5934157/125180605-b8737480-e1b0-11eb-89ea-0612c24fd64a.mp4

And on Linux:

https://user-images.githubusercontent.com/5934157/125202323-f2cc2880-e227-11eb-917e-57d2280e97a3.mp4

Thanks @mason-fish!
