### ISSUE TITLE
Zeek standalone vs. Brim speed

### ISSUE THREAD

**Issue by aziel12** [brimdata/brim#1832]
Hello, sry I didnt know where I can ask this general question, sry if it is in wrong thread..
Question: I am currently comparing zeek standalone to brim in times of analyzing single big pcapfile. Brim is very fast, eg: zeek -Cr 500MB_file.pcap takes 1min40sec, Brim finish much faster. So question is, does brim use zeek internally somehow multithreaded? Because zeek -Cr file.pcap is always singlethreadded. 
Thanks

**Comment by philrz** [comment]
@aziel12: Thanks for your interest in Brim. I saw your inquiry on the Zeek mailing list as well.

I'm not sure how to explain your perceived faster behavior in Brim. It does use Zeek to turn pcaps into logs, but it doesn't do anything special to make Zeek multi-threaded in ways it otherwise wouldn't be. If you look into the code on our repos you'll see that when Zeek is called it's the exact same `-C -r myfile.pcap` kind of command line you describe. I'm not sure what platform you're testing on, but for instance if you drag a pcap into Brim on a multi-core Linux system while watching the output of `top`, you'll see that the Zeek process almost never gets above 100%, which is confirmation that it's only ever fully consuming one core. Here's an example of me doing that after having dragged a random 500 MB pcap into Brim:

```
$ top -b | grep -i zeek
10739 phil      20   0 1973048 395612  23472 R 100.0  9.8   0:16.06 zeek
10739 phil      20   0 1982288 404852  23472 R  76.4 10.0   0:18.36 zeek
10739 phil      20   0 1982552 405324  23704 S  75.2 10.1   0:20.63 zeek
10739 phil      20   0 1989944 412716  23704 R  53.3 10.2   0:22.24 zeek
10739 phil      20   0 2010936 433872  23744 R  95.7 10.8   0:25.13 zeek
10739 phil      20   0 2062784 484916  23744 S  86.8 12.0   0:27.75 zeek
10739 phil      20   0 2083916 506320  24072 R  92.7 12.6   0:30.54 zeek
10739 phil      20   0 2099500 521896  24072 R  89.4 12.9   0:33.23 zeek
10739 phil      20   0 2117460 540112  24072 R  99.3 13.4   0:36.22 zeek
10739 phil      20   0 2124196 547192  24320 R  69.9 13.6   0:38.33 zeek
10739 phil      20   0 2124988 547828  24444 R  63.5 13.6   0:40.24 zeek
10739 phil      20   0 2126572 549412  24444 R  52.2 13.6   0:41.81 zeek
10739 phil      20   0 2127100 550528  24820 R  58.9 13.7   0:43.59 zeek
10739 phil      20   0 2129080 552544  25024 R  59.8 13.7   0:45.39 zeek
10739 phil      20   0 2129608 553072  25024 R  55.6 13.7   0:47.07 zeek
10739 phil      20   0 2130136 553600  25024 R  46.4 13.7   0:48.47 zeek
10739 phil      20   0 2131984 555448  25024 R  50.0 13.8   0:49.98 zeek
10739 phil      20   0 2133040 556504  25024 R  56.5 13.8   0:51.68 zeek
10739 phil      20   0 2133040 556504  25024 S  65.6 13.8   0:53.66 zeek
10739 phil      20   0 2133040 556504  25024 R  56.5 13.8   0:55.36 zeek
10739 phil      20   0 2133040 556820  25096 S  68.8 13.8   0:57.43 zeek
10739 phil      20   0 2133040 556820  25096 S  59.9 13.8   0:59.24 zeek
10739 phil      20   0 2133244 557072  25420 R  99.0 13.8   1:02.22 zeek
10739 phil      20   0 2209940 558724  25424 S 136.8 13.9   1:06.35 zeek
```

Depending on how you're running your standalone Zeek, there may be other ways to explain the performance difference. To name two I can think of off the top:

1.  The Zeek that's bundled with Brim is older than the latest. It's based on Zeek v3.2.1, whereas the latest GA is v4.1.0. If you're testing your standalone with more recent Zeek, perhaps there's some newer features consuming additional resources that's making it run longer.
2.  Maybe there's additional Zeek scripts being invoked in the standalone testing that are consuming additional resources.

I'm sure there's other possible explanations as well.

**Comment by aziel12** [comment]
Thank you Phil for your reply. What is the best (recommended) way of analysing big single (500MB-2GB) pcap file? If Brim calls zeek same way, is there anyway to make zeek -r file.pcap somehow multithreadable, so it reads with all available CPU cores that only one.

**Comment by philrz** [comment]
@aziel12: Sorry, I can't speak to a way to achieve that. For the purposes of this topic, we're basically just "a Zeek user" much like yourself. I think you brought the question to the right place by posting on the Zeek mailing list, though based on prior experience, you might not get the response you're looking for. As Brim is a tool that relies on Zeek's pcap processing, I've found that bigger-scale features like listening to live interfaces & doing things in cluster mode seem to get more attention from Zeek's core Dev team when compared to things like the speed of single-file pcap processing. But maybe you'll luck out and they'll come back with something encouraging. I'll certainly be watching for a response as well!

**Comment by philrz** [comment]
@aziel12: As I've shared all the info I can think of that would be relevant to your question, I'm going to go ahead and close this issue. Feel free to come talk to us on the [Brim public Slack](https://www.brimsecurity.com/join-slack/) if you'd like to discuss further.
