### ISSUE TITLE
Importing small files results in jumpy UI

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1911]
When dragging a small zson file into brim, the UI jumps around a lot very quickly before showing the data. 

https://user-images.githubusercontent.com/3460638/139709801-293e689c-d717-4c5c-8cb2-745da17ce65b.mp4

When dragging in big files, we present a very poor empty state. It looks like nothing is working. This was because we used to commit partial data to the pool and made that searchable, but now we wait for the whole file to be loaded before showing any data. Let's design a better UI for the loading state. This is what it looks like for minutes when you drag in a big pcap file:

<img width="1010" alt="Screen Shot 2021-11-01 at 10 33 59 AM" src="https://user-images.githubusercontent.com/3460638/139714919-e11bf742-3e4f-446e-bee5-906b8ec28925.png">

**Comment by philrz** [comment]
@jameskerr: It seems we've evolved a bit in both the areas deemed lacking the initial issue description. I've taken some videos with Brim commit 5226183 to capture current conditions.

For the small file import, it seems the "jumpy"-ness has been lessened by the fact that the user now pauses that the pool summary screen and then clicks Query Pool.

https://user-images.githubusercontent.com/5934157/186295454-929f0d42-e4b2-4701-a8b6-e82d7946fbbf.mp4

For the large pcap import, the user still has to wait, but instead of only having the subtle progress bar in the left sidebar, now they also have the spinner next to the "Waiting for pool to become queryable..." front & center in the main results window. So, short of bringing back the showing of "partial results" (which has been deemed difficult in the pool era) or offering the user a game to play while they wait [ 😄 ] I sense we might be doing as well as we could for that one right now.

https://user-images.githubusercontent.com/5934157/186295463-d9c1a7c3-2866-4d84-a7ae-d16530fca97a.mp4

If you still want the reminder to think more about one/both of these areas in the future, I'm happy to hold this one open. Or if you agree that we're in good enough shape, I'd also be happy to close it. Your call.

**Comment by jameskerr** [comment]
Let's close this. The current behavior is good.
