### ISSUE TITLE
Cache searches in tab history

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1917]
Cache the results from the last x searches so that when when we bounce back and forth with the forward and back buttons, things load super fast.

**Comment by philrz** [comment]
Seems like a nice enhancement, though my inner perfectionist wonders if we have to deal with the possibility that the data in the underlying pool(s) might change in the time since the results were cached. Would there be a way (maybe using the events system?) for the app to be notified when certain pool(s) have changed and then invalidate the corresponding cache entries?

**Comment by jameskerr** [comment]
I agree Phil. I'd be fine closing this issue.

**Comment by philrz** [comment]
Thanks @jameskerr. Based on that I'll go ahead and close this one as a "won't fix". If we decide that caching would help here in the future we can revisit the topic.
