### ISSUE TITLE
Typing in relative dates breaks the app

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1929]
Typing in the time range two relative times breaks the app with an error:

https://user-images.githubusercontent.com/3460638/139928575-6c4c30a2-7732-40b4-984b-d9f605901b19.mp4

Here is a screenshot of the error:

<img width="875" alt="Screen Shot 2021-11-02 at 12 01 15 PM" src="https://user-images.githubusercontent.com/3460638/139928593-f296f10f-fad2-4f8a-92bb-021b4993172c.png">

**Comment by mattnibs** [comment]
I ran into something weird when testing this feature. As long as I type in the expected string value everything is fine. For instance if I type `last 3 seconds` this is recognized. However weird stuff happens if it doesn't get something it expects:

- typing `last 3 sec` while displaying a value gives me `!!!` in the date picker but `last 3 seconds` of `last 3 second` works fine. I think `last 3 sec` is getting recognized as a time in the future.
- `3 sec` assumes time in the future when I think this should be unrecognized.
- `3 sec blah` works and assumes 3 seconds in the future
- If I do `3 sec from now` in to, wait 3 seconds then type `last 3 sec` I get the `!!!` error. I suppose this is because it doesn't recognize `now` +- a relative time. EDIT it does you just have to do `now - 3 s`.
- `now - 3 s` works but `now - 3 second|seconds|sec|secs` does not.
- `last 3 s|secs` does not work.
- microseconds/nanoseconds are not supported but the backend does support this.
- `7 years - now` gives me `now`. This should probably be an error.

A couple thoughts:
- It wasn't immediately obvious to me that `!!!` means from > to
- It is kind of confusing when a time is not recognized I don't get an error and the previous time remains.
- Obviously getting 100% correct to users expectations would require some kind of NLP which is a difficult problem. I'm thinking instead of needing to get every user whim right we could:
  1. Make it more obvious when something isn't recognized.
  2. Fix the cases where it works but shouldn't (i.e. `7 years - now` or `7 years blah`)
  3. Include a link near the time picker to a github markdown file that specifies what relative times are allowed.
