### ISSUE TITLE
Related alerts in detail pane never finishes loading

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#1930]
The loading indicator never disappears in the related alerts panel on the detail pane.

https://user-images.githubusercontent.com/3460638/139929348-d3d0b3cc-7dea-42ca-97dd-03b5fcad7e2f.mp4

There were no errors in the dev console.

**Comment by philrz** [comment]
I took a look to confirm where this got fixed. I have some difficulty building some of the older Brim versions in Dev mode, so I used some nightly builds. I was last able to repro this one with build https://storage.googleapis.com/brimsec-releases/brim/v0.28.0-prerelease-8782586a.0/macos/Brim-0.28.0-prerelease-8782586a.0.dmg and first saw it fixed on build https://storage.googleapis.com/brimsec-releases/brim/v0.28.0-prerelease-abf81ccc.0/macos/Brim-0.28.0-prerelease-abf81ccc.0.dmg. The only commit between these two was deafac3 which was an advance in the Zed pointer, but the Zed changes appear to be just related to ztests. Therefore it would seem that the changes in #1956 were what fixed this.

**Comment by philrz** [comment]
Also, since the changes in #1956 don't immediately look like they'd affect this functionality, I double checked with @jameskerr and he confirmed that the reason for closing this bug was because the correlations functionality was significantly rewritten #2455 and this symptom is certainly long gone now.
