### ISSUE TITLE
app does not display data without ts field when pool-key is ts

### ISSUE THREAD

**Issue by mccanne** [brimdata/brim#1955]
create two pools

```
zed create a 
zed create -orderby x b
```

(so pool `a` has by default pool key `ts`)  
load them with this file `in.zson`

```
{ts:2021-11-08T13:14:20Z,s:"a"}
{s:"c",a:[1]}
```

via

```
zed load -use a@main in.zson
zed load -use b@main in.zson
```

Click on pool `a` and you won't see the second record.  
Click on pool`b` and you will see both.

**Comment by philrz** [comment]
I've verified via binary search that this issue was fixed starting at Brim commit 712f227, which is associated with the changes in #2362.

The video below shows it working correctly as of current Brim commit ebc950d7. Both records show up in both pools.

https://user-images.githubusercontent.com/5934157/179876763-cc97d815-b44f-46b6-863a-cc0e69b6b21b.mp4

Thanks @mason-fish!
