### ISSUE TITLE
Export results breaks with secure lake

### ISSUE THREAD

**Issue by mason-fish** [brimdata/brim#1970]
When connected to an auth0-secured lake, exporting results from the app is broken. I've tracked this down to `exportResults.ts` where we are not using zealot to fully facilitate this request, and because of this we don't send the accompanying auth credentials.

**Comment by philrz** [comment]
I've verified that this one seems to have been fixed by the changes in #2427.

Taking a step back, the first video below is a repro of the issue as of Brim commit 1484e80 that was right before the changes from #2427. As shown, the results file being generated contains only control messages and no actual ZNG data.

https://user-images.githubusercontent.com/5934157/186011745-35fd1927-f07d-4d31-9a1d-f32550f1b3d0.mp4

While also verified the fix as of the next Brim commit 97b7049 that was associated with the changes in #2427, the verification video below was taken with current Brim commit 9912a29. As this shows, the results being sent back are now large/binary and representative of what we expect from ZNG data.

https://user-images.githubusercontent.com/5934157/186012029-a99028e4-e978-46eb-bd1f-2655e4bca002.mp4

Closing this as fixed.
