### ISSUE TITLE
CSS bug in sidebar

### ISSUE THREAD

**Issue by jameskerr** [brimdata/brim#2220]
When the sidebar gets too small, you see the plus button breaking out of it's container.

![image.png](https://images.zenhubusercontent.com/5e8cea85d10cba8a99efeb34/30e7c718-2daf-4e57-b0ac-9df5b511abb5)

**Comment by philrz** [comment]
I noticed this issue was hanging out in the "Done" column but didn't have a linked PR, so I did some quick digging and confirmed that it was indeed fixed by the changes in #2403.

Here's a quick refresher of how things were still broken at Brim commit ae5bf49 that came right before the fix:

https://user-images.githubusercontent.com/5934157/178365625-f7e0390d-4719-4a13-9ff1-4a7ed7e298ae.mp4

And here's the verification of it being fixed as of Brim commit 4ce41d6, which reflect the #2403 changes:

https://user-images.githubusercontent.com/5934157/178365711-e3a12d9b-b6e8-4fbe-9238-2b2e7e7199ab.mp4

Thanks @mason-fish!
