### ISSUE TITLE
Brim v0.30.0  Suricata Runner menù not appear.

### ISSUE THREAD

**Issue by Dariosniper** [brimdata/brim#2368]
Hi all,

after finish to install Brim, i go to Settings --> Preferences for setup the Suricata Runner but the menù not appear.

below the screen
![image](https://user-images.githubusercontent.com/15210574/170665992-c5ceab77-6e91-438a-b551-d948f333e0fc.png)

thanks for support

**Comment by philrz** [comment]
@Dariosniper: Starting with Brim `v0.25.0`, functionality related to pcap processing (such as generating summary Suricata/Zeek logs from pcaps) is now handled by a separate tool called [Brimcap](https://github.com/brimdata/brimcap), which is bundled with Brim. Configurations with customized Suricata/Zeek are therefore now handled via Brimcap as well, and this is described in the [Custom Brimcap Config](https://github.com/brimdata/brimcap/wiki/Custom-Brimcap-Config) article in the Brimcap wiki. While I expect an experienced user could follow that article to recreate the custom configs they'd used in the past, I'm aware that it's a bit out-of-date and in need of some updates to reflect recent changes in the tooling. Since I know this is a topic of interest for you, I'll prioritize making those updates in the next couple days and comment here when the newer article is ready. If you're in a hurry to get started by going off what's in the article today, if you hit any problems just speak up on the [Brim community Slack](https://www.brimdata.io/join-slack/) and I'd be happy to help.

**Comment by philrz** [comment]
@Dariosniper: There's an open PR #250 awaiting review that includes the necessary updates to the Custom Brimcap Config article. If you're looking to get a jump on it before it's reviewed/merged, you can find the draft of the article in my fork branch at https://github.com/philrz/brimcap/blob/main/docs/Custom-Brimcap-Config.md. I'll update here when it does get merged and is available in its final home.
