### ISSUE TITLE
is it possible this could be made available in pypi?

### ISSUE THREAD

**Issue by milti** [brimdata/brim#2473]
i want to bring brimdata into my teams workflow, but the admins of our central system have issues w the building the RPM and the licensing. 

can this be made available in pypi? that way i could localise the install and make a PoC case for the tool.

but there is simply no way i can install via YUM/DNF locally

**Comment by milti** [comment]
to make a clarification, im not so much looking for the desktop tool, as the brimcap/zed/zq components to be used from a CLI.

**Comment by philrz** [comment]
@milti: Thanks for your interest in the projects.

A couple of us on the Brim team have read this issue and admit to some limits in our PyPi knowledge. Personally we're only familiar with PyPi's primary mission as described at https://pypi.org/ to "install and publish Python packages". In this regard, it seems like the [Zed Python library](https://zed.brimdata.io/docs/next/libraries/python/) might

**Comment by philrz** [comment]
@milti: Thanks for your interest in the projects.

A couple of us on the Brim team have read this issue and admit to some limits in our PyPi knowledge. Personally we're only familiar with PyPi's primary mission as described at https://pypi.org/ to "install and publish Python packages". In this regard, it seems like the [Zed Python library](https://zed.brimdata.io/docs/next/libraries/python/) might be something we could look to start distributing via PyPi, but I'm less sure how the non-Python binaries you mention like `brimcap`, `zed`, and `zq` would be distributed via PyPi. I did some web searches to see if I could find examples of such non-Python tools being packaged and distributed and did find some StackOverflow threads and other resources where it was loosely discussed. But since it sounds like you know the use case better than we do, rather than guess at what you had in mind and risk taking the wrong approach, would it be possible for you to point to some other project/tool that's distributed in your ideal way that we could study for precedent?

Separate from that angle, since you also stated your problem as being that YUM/DNF are a non-starter, I feel I should also make sure you're aware that unlike the Brim app that we make available as DEB/RPM/DMG/EXE based on OS platform, for those tools you mention like `brimcap` and `zed`/`zq`, a common way to distribute/install is by downloading and unpacking the ZIP artifacts from https://github.com/brimdata/brimcap/releases and https://github.com/brimdata/zed/releases, respectively. Could you help us understand if/why that's not viable?

**Comment by milti** [comment]
sorry for the delay in responding: i will look at d'loading/unpacking the artifacts to move forward.
