### ISSUE TITLE
CSV Export settings (delimiter, quotecharacter)

### ISSUE THREAD

**Issue by omnidepp** [brimdata/brim#2577]
Hi all,
my CSV exports break, when a field contains a comma. Is there the possibility to add settings for the delimiter and quoting?
Kind regards

**Comment by philrz** [comment]
@omnidepp: I'd like to make sure I fully understand before asking the Dev team to look into this closer. Am I correct in thinking that your problem is not a failure in the Export operation in Brim itself, but with tool you're trying to load the generated CSV file into? It would be most helpful if you could post some simple sample data that illustrates the problem and describe what you'd want to see instead with the use of the settings you've proposed. If I'm correct in guessing that it's a downstream tool that's the problem, it'd also help if you could say what the tool is, as I know these debates about CSV dialects often detour into understanding the what & why of non-RFC4180 compliance. Thanks!

**Comment by omnidepp** [comment]
@philrz : you are right: upon further testing, I noticed that brim does indeed quote fields if they contain a comma. So it is something I can handle on my end. I guess I was just too used to picking whatever delimiter or quoting I wanted, no matter the specification - so I'm closing this.
