### ISSUE TITLE
brim can only display the first 500 rows of data

### ISSUE THREAD

**Issue by burpheart** [brimdata/brim#2624]
Before opening a new issue, please make sure you've reviewed the troubleshooting guide:
https://github.com/brimdata/brim/wiki/Troubleshooting

**Describe the bug**
brim can only display the first 500 rows of data

**To Reproduce**
test.json
{"id":1}
{"id":2}
{"id":3}
{"id":4}
......
{"id":9999}
{"id":10000}

**Expected behavior**
 | id | 
 1
 2
 3
 4
......
 9999
 10000

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/35721255/208282123-691a313e-08e7-4a3e-9629-f51a93b200f8.png)

**Desktop Info**
 - OS: Windows
 - Brim Version: 0.31.0

**Comment by philrz** [comment]
@burpheart: Thanks for reporting. This is a limitation that's been addressed and therefore won't be in the next release which will be called Zui v1.0. You can read our [blog post](https://www.brimdata.io/blog/brim-app-will-be-zui/) for more details on the transition. As mentioned there, if you're ok using a beta-style release for now, you can start using Zui Insiders today to take advantage of that fix and other improved functionality. I'll hold this issue open in case you have any questions about that.

**Comment by philrz** [comment]
@burpheart: Since I've not seen any further comments here, I'm going to go ahead and close this issue on the assumption that you'll be able to take advantage of the fix in Zui Insiders for now. If you need any help with that I'd recommend joining the [community Slack](https://www.brimdata.io/join-slack/) and joining the `#zui-insiders` channel. Thanks for your interest in Brim!
